
export const SETTINGS_TEXT = {
  title: "Configurações",
  tabs: {
    profile: "Perfil",
    preferences: "Preferências",
    whatsapp: "WhatsApp"
  },
  appearance: "Aparência",
  appearanceDescription: "Personalize a aparência do aplicativo",
  appearanceUpdated: "Aparência atualizada com sucesso",
  darkMode: "Modo escuro",
  darkModeDescription: "Alterne entre tema claro e escuro",
  chatPreferences: "Preferências de Chat",
  chatPreferencesDesc: "Configure suas preferências de chat",
  enableAI: "Ativar IA",
  enableAIDesc: "Permite que a IA ajude com suas finanças",
  security: "Segurança",
  securityDesc: "Gerencie as configurações de segurança",
  twoFactor: "Autenticação em dois fatores",
  twoFactorDesc: "Adicione uma camada extra de segurança",
  notifications: "Notificações",
  notificationsDesc: "Gerencie suas preferências de notificação",
  pushNotifications: "Notificações push",
  pushNotificationsDesc: "Receba notificações importantes",
  notificationsDescription: "Controle quais alertas você deseja receber",
  spendingAlerts: "Alertas de gastos",
  spendingAlertsDescription: "Receba alertas quando seus gastos ultrapassarem limites definidos",
  goalAchieved: "Metas atingidas",
  goalAchievedDescription: "Seja notificado quando atingir suas metas financeiras",
  autoSuggestions: "Sugestões automáticas",
  autoSuggestionsDescription: "Receba dicas personalizadas para melhorar suas finanças",
  preferencesUpdated: "Preferências atualizadas com sucesso",
  whatsapp: "Integração WhatsApp",
  whatsappDescription: "Registre transações diretamente pelo WhatsApp",
  whatsappStatus: "Status da Conexão",
  whatsappConnected: "Conectado",
  whatsappNotConnected: "Não conectado",
  manageConnection: "Gerenciar",
  connectWhatsapp: "Conectar WhatsApp",
  whatsappTips: "Como usar o WhatsApp",
  whatsappTip1: "Envie mensagens como \"Gastei R$50 no mercado\"",
  whatsappTip2: "Transações serão adicionadas automaticamente",
  whatsappTip3: "Suporte a várias categorias de despesas"
};
