
export const TRANSACTIONS_TEXT = {
  title: "Transações",
  subtitle: "Visualize e gerencie todas as suas transações financeiras",
  date: "Data",
  type: "Tipo",
  category: "Categoria",
  description: "Descrição",
  descriptionPlaceholder: "Ex: Supermercado",
  amount: "Valor",
  actions: "Ações",
  recurring: "Transação Recorrente",
  frequency: "Frequência",
  addNew: "Adicionar Nova Transação",
  add: "Adicionar Transação",
  addDescription: "Preencha os detalhes da nova transação",
  editTitle: "Editar Transação",
  editDescription: "Modifique os detalhes da transação abaixo",
  deleteTitle: "Excluir Transação",
  deleteConfirmation: "Tem certeza que deseja excluir esta transação? Esta ação não pode ser desfeita.",
  delete: "Excluir",
  deleteSuccess: "Transação excluída",
  transactionDeletedMessage: "Sua transação foi excluída.",
  deleteError: "Falha ao excluir transação",
  updateSuccess: "Transação atualizada com sucesso",
  updateError: "Falha ao atualizar transação",
  save: "Salvar alterações",
  undo: "Desfazer",
  restoreSuccess: "Transação restaurada",
  restoreDescription: "Sua transação foi restaurada.",
  removeRecurring: "Remover recorrência",
  setRecurring: "Tornar recorrente",
  expense: "Despesa",
  income: "Receita",
  allTransactions: "Todas as Transações",
  pageDescription: "Visualize, edite e gerencie suas transações",
  fetchError: "Erro ao carregar transações",
  addRecurring: "Adicionar Recorrente"
};
