
export const WHATSAPP_TEXT = {
  connection: "Conexão WhatsApp",
  description: "Conecte seu WhatsApp para registrar transações automaticamente",
  phoneNumberHint: "Inclua o código do país e DDD",
  connecting: "Conectando...",
  connect: "Conectar",
  updateConnection: "Atualizar Conexão",
  status: "Status da Conexão",
  statusDescription: "Detalhes da conexão do seu WhatsApp",
  connected: "Conectado",
  disconnected: "Desconectado",
  connectionSuccessful: "Conexão bem-sucedida!",
  startSendingMessages: "Agora você pode enviar mensagens para o número do WhatsApp Business para registrar transações.",
  connectionNeeded: "Conexão necessária",
  pleaseConnectNumber: "Por favor, insira seu número de WhatsApp para conectar ao sistema.",
  howToUse: "Como usar",
  howToUseDesc: "Instruções para usar o WhatsApp",
  examples: "Exemplos de mensagens",
  errorEmptyNumber: "Por favor, insira um número de telefone válido",
  successConnection: "WhatsApp conectado com sucesso!",
  errorConnection: "Erro ao conectar WhatsApp",
  active: "Ativo",
  phoneNumber: "Número",
  canReceiveMessages: "Recebimento habilitado",
  canReceiveMessagesDesc: "Você pode receber mensagens a qualquer momento.",
  canSendMessages: "Envio habilitado",
  canSendMessagesDesc: "Você pode enviar mensagens para registrar transações.",
  successWelcomeMessage: "Mensagem de boas-vindas enviada!",
  chatButton: "WhatsApp"
};
