
project_id = "jevsazpwfowhmjupuuzw"

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-test]
verify_jwt = false

[functions.parse-expense]
verify_jwt = false

[functions.generate-insights]
verify_jwt = false

[functions.send-whatsapp-welcome]
verify_jwt = false
