
project_id = "jevsazpwfowhmjupuuzw"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[[functions]]
name = "parse-expense"
verify_jwt = true

[[functions]]
name = "process-chat"
verify_jwt = true

[[functions]]
name = "check-whatsapp-number"
verify_jwt = true

[[functions]]
name = "whatsapp-webhook"
verify_jwt = false

[[functions]]
name = "whatsapp-test"
verify_jwt = false

[[functions]]
name = "send-whatsapp-welcome"
verify_jwt = true

[[functions]]
name = "generate-insights"
verify_jwt = true

[[functions]]
name = "send-password-email"
verify_jwt = true

[[functions]]
name = "send-email"
verify_jwt = true

[[functions]]
name = "parse-bank-statement"
verify_jwt = true
