
project_id = "jevsazpwfowhmjupuuzw"

[api]
enabled = true
port = 8080
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 5432
shadow_port = 5431
major_version = 15

[studio]
enabled = true
port = 8082
api_url = "http://localhost"

[inbucket]
enabled = true
port = 8084

[storage]
enabled = true
port = 8085

[auth]
enabled = true
port = 8083

[realtime]
enabled = true

[functions]
[functions.generate-insights]
verify_jwt = true
