
// Textos em português para a aplicação
export const TEXT = {
  common: {
    income: "Receita",
    expense: "Despesa",
    balance: "Saldo",
    savings: "Poupança",
    today: "Hoje",
    thisMonth: "Este Mês",
    lastMonth: "Mês Passado",
    upcoming: "Em breve",
    accumulated: "Acumulado",
    cancel: "Cancelar",
    error: "Erro",
    save: "Salvar",
    saving: "Salvando...",
    dashboard: "Visão Geral",
    transactions: "Transações",
    goals: "Metas",
    settings: "Configurações",
    user: "Usuário"
  },
  header: {
    dashboard: "Painel",
    addExpense: "Nova Transação",
    settings: "Configurações",
    whatsappSetup: "Configurar WhatsApp",
    logout: "Sair"
  },
  dashboard: {
    title: "Painel de Controle",
    subtitle: "Acompanhe suas finanças e analise seus hábitos de gastos",
    welcome: "Bem-vindo ao seu painel financeiro! Aqui você pode acompanhar suas finanças de forma rápida.",
    fromLastMonth: "do mês anterior",
    tabs: {
      overview: "Visão Geral",
      transactions: "Transações",
      analytics: "Análises"
    },
    charts: {
      categoryBreakdown: "Para onde foi seu dinheiro este mês",
      incomeByType: "Fontes de receita",
      dailyEvolution: "Movimentações diárias",
      balanceByAccount: "Saldo por conta/cartão",
      revenueVsExpense: "Receita vs Despesa (últimos 6 meses)",
      financialGoals: "Metas financeiras",
      balanceEvolution: "Evolução do saldo",
      noData: "Sem dados para exibir",
      noGoals: "Nenhuma meta de economia encontrada",
      createGoal: "Criar uma meta",
      day: "Dia",
      amount: "Valor"
    },
    bigNumbers: {
      income: "Receita",
      expenses: "Despesas",
      balance: "Saldo",
      savings: "Poupança",
      availableBalance: "Saldo Disponível",
      availableBalanceTooltip: "Seu saldo disponível atual em todas as contas",
      monthlyExpenses: "Despesas Mensais",
      monthlyExpensesTooltip: "Total de despesas do mês atual",
      monthlyIncome: "Receita Mensal",
      monthlyIncomeTooltip: "Total de receitas do mês atual",
      pendingBalance: "Saldo Pendente",
      pendingBalanceTooltip: "Transações agendadas futuras",
      totalSavings: "Total de Economias",
      totalSavingsTooltip: "Suas economias acumuladas em todas as metas",
      today: "Hoje",
      thisMonth: "Este Mês",
      upcoming: "Em breve",
      accumulated: "Acumulado"
    },
    emptyState: {
      message: "Comece a registrar para ver seus dados"
    }
  },
  transactions: {
    title: "Transações",
    subtitle: "Visualize e gerencie todas as suas transações financeiras",
    date: "Data",
    type: "Tipo",
    category: "Categoria",
    description: "Descrição",
    descriptionPlaceholder: "Ex: Supermercado",
    amount: "Valor",
    actions: "Ações",
    recurring: "Transação Recorrente",
    frequency: "Frequência",
    addNew: "Adicionar Nova Transação",
    add: "Adicionar Transação",
    addDescription: "Preencha os detalhes da nova transação",
    editTitle: "Editar Transação",
    editDescription: "Modifique os detalhes da transação abaixo",
    deleteTitle: "Excluir Transação",
    deleteConfirmation: "Tem certeza que deseja excluir esta transação? Esta ação não pode ser desfeita.",
    delete: "Excluir",
    deleteSuccess: "Transação excluída",
    deleteDescription: "Sua transação foi excluída.",
    deleteError: "Falha ao excluir transação",
    updateSuccess: "Transação atualizada com sucesso",
    updateError: "Falha ao atualizar transação",
    save: "Salvar alterações",
    undo: "Desfazer",
    restoreSuccess: "Transação restaurada",
    restoreDescription: "Sua transação foi restaurada.",
    removeRecurring: "Remover recorrência",
    setRecurring: "Tornar recorrente",
    expense: "Despesa",
    income: "Receita",
    allTransactions: "Todas as Transações",
    description: "Visualize, edite e gerencie suas transações",
    fetchError: "Erro ao carregar transações",
    addRecurring: "Adicionar Recorrente"
  },
  whatsapp: {
    connection: "Conexão WhatsApp",
    description: "Conecte seu WhatsApp para registrar transações automaticamente",
    phoneNumberHint: "Inclua o código do país e DDD",
    connecting: "Conectando...",
    connect: "Conectar",
    status: "Status",
    statusDescription: "Seu número está conectado",
    connected: "Conectado",
    howToUse: "Como usar",
    howToUseDesc: "Instruções para usar o WhatsApp",
    examples: "Exemplos de mensagens",
    errorEmptyNumber: "Por favor, insira um número de telefone válido",
    successConnection: "WhatsApp conectado com sucesso!",
    errorConnection: "Erro ao conectar WhatsApp"
  },
  settings: {
    title: "Configurações",
    tabs: {
      profile: "Perfil",
      preferences: "Preferências",
      whatsapp: "WhatsApp"
    },
    appearance: "Aparência",
    appearanceDescription: "Personalize a aparência do aplicativo",
    appearanceUpdated: "Aparência atualizada com sucesso",
    darkMode: "Modo escuro",
    darkModeDescription: "Alterne entre tema claro e escuro",
    chatPreferences: "Preferências de Chat",
    chatPreferencesDesc: "Configure suas preferências de chat",
    enableAI: "Ativar IA",
    enableAIDesc: "Permite que a IA ajude com suas finanças",
    security: "Segurança",
    securityDesc: "Gerencie as configurações de segurança",
    twoFactor: "Autenticação em dois fatores",
    twoFactorDesc: "Adicione uma camada extra de segurança",
    notifications: "Notificações",
    notificationsDesc: "Gerencie suas preferências de notificação",
    pushNotifications: "Notificações push",
    pushNotificationsDesc: "Receba notificações importantes",
    notificationsDescription: "Controle quais alertas você deseja receber",
    spendingAlerts: "Alertas de gastos",
    spendingAlertsDescription: "Receba alertas quando seus gastos ultrapassarem limites definidos",
    goalAchieved: "Metas atingidas",
    goalAchievedDescription: "Seja notificado quando atingir suas metas financeiras",
    autoSuggestions: "Sugestões automáticas",
    autoSuggestionsDescription: "Receba dicas personalizadas para melhorar suas finanças",
    preferencesUpdated: "Preferências atualizadas com sucesso",
    whatsapp: "Integração WhatsApp",
    whatsappDescription: "Registre transações diretamente pelo WhatsApp",
    whatsappStatus: "Status da Conexão",
    whatsappConnected: "Conectado",
    whatsappNotConnected: "Não conectado",
    manageConnection: "Gerenciar",
    connectWhatsapp: "Conectar WhatsApp",
    whatsappTips: "Como usar o WhatsApp",
    whatsappTip1: "Envie mensagens como \"Gastei R$50 no mercado\"",
    whatsappTip2: "Transações serão adicionadas automaticamente",
    whatsappTip3: "Suporte a várias categorias de despesas"
  },
  financialPlanning: {
    title: "Planejamento Financeiro",
    riskAlert: "Suas despesas previstas superam sua receita mensal.",
    availableToday: "Disponível Hoje",
    availableWeek: "Disponível na Semana",
    availableMonth: "Disponível no Mês",
    dailyTooltip: "Valor disponível para gastar hoje, considerando suas receitas e despesas",
    weeklyTooltip: "Valor disponível para gastar esta semana",
    monthlyTooltip: "Valor disponível para gastar este mês",
    simulation: "Simulação de Gasto",
    calculate: "Calcular impacto",
    clear: "Limpar simulação",
    negativeBalanceWarning: "Com esse gasto, você ficaria com saldo negativo em algum período.",
    recurringExpenses: "Despesas Recorrentes",
    noRecurringTransactions: "Você ainda não tem despesas recorrentes cadastradas.",
    addRecurringHint: "Adicione suas despesas fixas como aluguel, streaming, academia, etc."
  },
  auth: {
    confirmLogout: "Confirmar Saída",
    logoutConfirmation: "Tem certeza que deseja sair? Sua sessão será encerrada.",
    logout: "Sair"
  },
  common: {
    daily: "Diária",
    weekly: "Semanal",
    monthly: "Mensal",
    yearly: "Anual",
    processing: "Processando...",
    cancel: "Cancelar",
    attention: "Atenção"
  }
};
